# Generated by Django 4.2.6 on 2023-10-24 03:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('num_camiones', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('total_peso', models.FloatField(default=0.0)),
                ('peso_camion_vacio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_camion_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_saco_cafe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_exacto_carga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especial', models.BooleanField(default=False)),
                ('defectuoso', models.BooleanField(default=False)),
                ('cambio_contenedor', models.BooleanField(default=False)),
                ('cambio_camion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100)),
                ('peso_camion_vacio', models.FloatField(default=0.0)),
                ('peso_camion_total', models.FloatField(default=0.0)),
                ('peso_saco_cafe', models.FloatField(default=0.0)),
                ('total_sacos_cafe', models.IntegerField(default=0)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camiones', to='carga_camion.carga')),
            ],
        ),
    ]
